### ISSUE TITLE
Research | Other Ordering System (2/4)

### ISSUE THREAD

**Issue by brett-k-cs** [CSAllenISD/2023-ISP-SchoolFood#6]
Record:
- the name of the app
- the navigation menu
- the login system
- the customization screen
- anything that stands out as helpful or annoying
- customer reviews

**Comment by brett-k-cs** [comment]
Started researching the McDonalds app - https://docs.google.com/document/d/1geil7bljLc7oToRco6qx7oBvIeJxFFohpyQWk3JTyKU/edit?usp=sharing

**Comment by Rupak-B** [comment]
Started researching Chick Fil A app - 
https://docs.google.com/document/d/19LN--y7-e-iNghoO0SRPlZLJqxmrlgQlGLrKj414-LM/edit#

**Comment by Rupak-B** [comment]
Darsh and Hamza please start the research process. Update it on Github with a link to your research, please.

**Comment by DarshRA** [comment]
Done
